#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require(__DIR__.'/../../autoload.php');
} else {
    require(__DIR__.'/vendor/autoload.php');
}
set_time_limit(0);
$app = new Symfony\Component\Console\Application('PrestaShop Installer', '1.0');
$app->add(new \SDuval\Prestashop\Manager\Console\NewCommand());
$app->add(new \SDuval\Prestashop\Manager\Console\InstallCommand());
$app->add(new \SDuval\Prestashop\Manager\Console\ThemeCommand());
$app->run();